%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 752
image_height: 480
distortion_parameters:
   k1: -0.01
   k2: 0.004
   p1: 5e-5
   p2: -1e-4
projection_parameters:
   fx: 376
   fy: 376
   cx: 376
   cy: 240