%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 2  

imu_topic: "/djiros/imu"
image0_topic: "/stereo/left/image"
image1_topic: "/stereo/right/image"
output_path: "/home/dji/output/"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 512
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -2.6001622181574202e-02, -5.2085872909730102e-03,
       -9.9964833129574060e-01, -1.2886997952961168e-01,
       9.9965481566775383e-01, 3.6294078574090616e-03,
       -2.6020701583033656e-02, -1.2147595522352593e-01,
       3.7636626038181076e-03, -9.9997984880548296e-01,
       5.1124188763960188e-03, 3.2881561191272578e-02, 0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -2.3877053002065107e-02, -1.2793564889566844e-02,
       -9.9963303818819083e-01, -1.0696526695209820e-01,
       9.9968048539671106e-01, 7.9915246532147322e-03,
       -2.3980463938659879e-02, 3.8910400198456374e-03,
       8.2953876903301693e-03, -9.9988622364303725e-01,
       1.2598663101044294e-02, 3.1956268205111153e-02, 0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

